std_msgs/Header header
auto_msgs2/FromAutobox fromauto_msg
---
std_msgs/Header header
int64 exit_flag
float64 total_time
float64[] t_cmd_s
float64[] s_cmd_m
float64[] fx_1
float64[] fx_2
float64[] delta_1
float64[] delta_2
float64[] ux_1
float64[] ux_2
float64[] uy_1
float64[] uy_2
float64[] r_1
float64[] r_2
float64[] delta_cmd_rad
float64[] fx_cmd_kn
